apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.global.appName }}-api
  labels:
    app: {{ .Values.global.appName }}-api
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.global.appName }}-api
  template:
    metadata:
      labels:
        app: {{ .Values.global.appName }}-api
    spec:
      containers:
      - name: api
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 80
        imagePullPolicy: {{ .Values.image.pullPolicy }}