apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.global.appName }}-service
  labels:
    app: {{ .Values.global.appName }}
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 80
  selector:
    app: {{ .Values.global.appName }}-api