replicaCount: 2
image:
  repository: myrepo/api
  pullPolicy: IfNotPresent
  tag: "latest"
service:
  name: api-service
  type: ClusterIP
  port: 80
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: api.example.com
      paths:
        - path: /
          pathType: ImplementationSpecific
