apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Values.global.dbName }}-network-policy
spec:
  podSelector:
    matchLabels:
      app: {{ .Values.global.dbName }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
      - podSelector:
          matchLabels:
            app: {{ .Values.global.appName }}-api
  egress:
    - to:
      - podSelector:
          matchLabels:
            app: {{ .Values.global.appName }}-api