apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.global.dbName }}-postgresql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.size }}