apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.global.dbName }}-service
  labels:
    app: {{ .Values.global.dbName }}
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}
  selector:
    app: {{ .Values.global.dbName }}-postgresql